<?php
/**
 * SalesApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Central do desenvolvedor - Nexlog API
 *
 * De maneira pratica e rápida, entenda como conectar e consumir todas as informações necessárias para seu negócio. </br> <h2> Ambientes</h2> Os ambientes do gateway de integração são divididos atualmente em 2 ambientes:<br> &ensp;&ensp;&ensp;&ensp;&ensp;<b>QA</b>:&ensp;ambiente utilizado para desenvolvimento de novas integrações e testes com os clientes e parceiros.<br>&ensp;&ensp;&ensp;<b>Prod</b>:&ensp;ambiente de produção com todas os serviços expostos com certificação de qualidade. </br> <h2>Informações Adicionais</h2>                 A central do desenvolvedor conta com uma completa documentação referente a todos os APIs expostos, com exemplos de request/response, modelo e possibilidade de realizar testes direto no barramento. </br></br> Atualmente nossa central está separada com 2 dominios de integração:</br>&ensp;&ensp;&ensp; <b>- Account</b> <br> &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Serviços para autenticação quando necessário.</br>&ensp;&ensp;&ensp; <b>- Sales</b> <br> &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Disponibilização de serviços para utilização de rastreio, cotações, minutas e documentos autorizados.<br>&ensp;&ensp;&ensp; <b>- Operations</b> <br> &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Disponibilização de consulta de bases operacionais.<br>(*)Dependendo do endpoint utilizado, algumas informações são obrigatórias, como identificador da aplicação/cliente e token.<br><br> Dúvidas sobre como utilizar, entre em contato br-operations@ttinteractive.com
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * SalesApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SalesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation quotationCalculateQuotation
     *
     * Retun a freight quotation based on parameters
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\QuotationRequest $model model (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\QuotationResponse
     */
    public function quotationCalculateQuotation($company_key, $model)
    {
        list($response) = $this->quotationCalculateQuotationWithHttpInfo($company_key, $model);
        return $response;
    }

    /**
     * Operation quotationCalculateQuotationWithHttpInfo
     *
     * Retun a freight quotation based on parameters
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\QuotationRequest $model (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\QuotationResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function quotationCalculateQuotationWithHttpInfo($company_key, $model)
    {
        $returnType = '\Swagger\Client\Model\QuotationResponse[]';
        $request = $this->quotationCalculateQuotationRequest($company_key, $model);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\QuotationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation quotationCalculateQuotationAsync
     *
     * Retun a freight quotation based on parameters
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\QuotationRequest $model (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function quotationCalculateQuotationAsync($company_key, $model)
    {
        return $this->quotationCalculateQuotationAsyncWithHttpInfo($company_key, $model)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation quotationCalculateQuotationAsyncWithHttpInfo
     *
     * Retun a freight quotation based on parameters
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\QuotationRequest $model (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function quotationCalculateQuotationAsyncWithHttpInfo($company_key, $model)
    {
        $returnType = '\Swagger\Client\Model\QuotationResponse[]';
        $request = $this->quotationCalculateQuotationRequest($company_key, $model);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'quotationCalculateQuotation'
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\QuotationRequest $model (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function quotationCalculateQuotationRequest($company_key, $model)
    {
        // verify the required parameter 'company_key' is set
        if ($company_key === null || (is_array($company_key) && count($company_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_key when calling quotationCalculateQuotation'
            );
        }
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling quotationCalculateQuotation'
            );
        }

        $resourcePath = '/sales/transportorder/quotation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($company_key !== null) {
            $headerParams['companyKey'] = ObjectSerializer::toHeaderValue($company_key);
        }


        // body params
        $_tempBody = null;
        if (isset($model)) {
            $_tempBody = $model;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded', 'text/plain', 'text/html']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation salesTransportorderCancelPost
     *
     * Cancel a booking.
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\CancelRequest $minute minute (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function salesTransportorderCancelPost($company_key, $minute, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        $this->salesTransportorderCancelPostWithHttpInfo($company_key, $minute, $session_id, $session_token, $user_id, $token, $station);
    }

    /**
     * Operation salesTransportorderCancelPostWithHttpInfo
     *
     * Cancel a booking.
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\CancelRequest $minute (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function salesTransportorderCancelPostWithHttpInfo($company_key, $minute, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        $returnType = '';
        $request = $this->salesTransportorderCancelPostRequest($company_key, $minute, $session_id, $session_token, $user_id, $token, $station);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation salesTransportorderCancelPostAsync
     *
     * Cancel a booking.
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\CancelRequest $minute (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function salesTransportorderCancelPostAsync($company_key, $minute, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        return $this->salesTransportorderCancelPostAsyncWithHttpInfo($company_key, $minute, $session_id, $session_token, $user_id, $token, $station)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation salesTransportorderCancelPostAsyncWithHttpInfo
     *
     * Cancel a booking.
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\CancelRequest $minute (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function salesTransportorderCancelPostAsyncWithHttpInfo($company_key, $minute, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        $returnType = '';
        $request = $this->salesTransportorderCancelPostRequest($company_key, $minute, $session_id, $session_token, $user_id, $token, $station);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'salesTransportorderCancelPost'
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\CancelRequest $minute (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function salesTransportorderCancelPostRequest($company_key, $minute, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        // verify the required parameter 'company_key' is set
        if ($company_key === null || (is_array($company_key) && count($company_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_key when calling salesTransportorderCancelPost'
            );
        }
        // verify the required parameter 'minute' is set
        if ($minute === null || (is_array($minute) && count($minute) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $minute when calling salesTransportorderCancelPost'
            );
        }

        $resourcePath = '/sales/transportorder/cancel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($company_key !== null) {
            $headerParams['companyKey'] = ObjectSerializer::toHeaderValue($company_key);
        }
        // header params
        if ($session_id !== null) {
            $headerParams['sessionId'] = ObjectSerializer::toHeaderValue($session_id);
        }
        // header params
        if ($session_token !== null) {
            $headerParams['sessionToken'] = ObjectSerializer::toHeaderValue($session_token);
        }
        // header params
        if ($user_id !== null) {
            $headerParams['userId'] = ObjectSerializer::toHeaderValue($user_id);
        }
        // header params
        if ($token !== null) {
            $headerParams['token'] = ObjectSerializer::toHeaderValue($token);
        }
        // header params
        if ($station !== null) {
            $headerParams['station'] = ObjectSerializer::toHeaderValue($station);
        }


        // body params
        $_tempBody = null;
        if (isset($minute)) {
            $_tempBody = $minute;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation salesTransportorderDacteDocumentNumberGet
     *
     * Get a transport order DACTE by document number
     *
     * @param  string $document_number The transport order document number. (required)
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function salesTransportorderDacteDocumentNumberGet($document_number, $company_key, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        list($response) = $this->salesTransportorderDacteDocumentNumberGetWithHttpInfo($document_number, $company_key, $session_id, $session_token, $user_id, $token, $station);
        return $response;
    }

    /**
     * Operation salesTransportorderDacteDocumentNumberGetWithHttpInfo
     *
     * Get a transport order DACTE by document number
     *
     * @param  string $document_number The transport order document number. (required)
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function salesTransportorderDacteDocumentNumberGetWithHttpInfo($document_number, $company_key, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        $returnType = '\SplFileObject';
        $request = $this->salesTransportorderDacteDocumentNumberGetRequest($document_number, $company_key, $session_id, $session_token, $user_id, $token, $station);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SplFileObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation salesTransportorderDacteDocumentNumberGetAsync
     *
     * Get a transport order DACTE by document number
     *
     * @param  string $document_number The transport order document number. (required)
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function salesTransportorderDacteDocumentNumberGetAsync($document_number, $company_key, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        return $this->salesTransportorderDacteDocumentNumberGetAsyncWithHttpInfo($document_number, $company_key, $session_id, $session_token, $user_id, $token, $station)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation salesTransportorderDacteDocumentNumberGetAsyncWithHttpInfo
     *
     * Get a transport order DACTE by document number
     *
     * @param  string $document_number The transport order document number. (required)
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function salesTransportorderDacteDocumentNumberGetAsyncWithHttpInfo($document_number, $company_key, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        $returnType = '\SplFileObject';
        $request = $this->salesTransportorderDacteDocumentNumberGetRequest($document_number, $company_key, $session_id, $session_token, $user_id, $token, $station);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'salesTransportorderDacteDocumentNumberGet'
     *
     * @param  string $document_number The transport order document number. (required)
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function salesTransportorderDacteDocumentNumberGetRequest($document_number, $company_key, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        // verify the required parameter 'document_number' is set
        if ($document_number === null || (is_array($document_number) && count($document_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_number when calling salesTransportorderDacteDocumentNumberGet'
            );
        }
        if ($document_number < 1) {
            throw new \InvalidArgumentException('invalid value for "$document_number" when calling SalesApi.salesTransportorderDacteDocumentNumberGet, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'company_key' is set
        if ($company_key === null || (is_array($company_key) && count($company_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_key when calling salesTransportorderDacteDocumentNumberGet'
            );
        }

        $resourcePath = '/sales/transportorder/dacte/{documentNumber}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($company_key !== null) {
            $headerParams['companyKey'] = ObjectSerializer::toHeaderValue($company_key);
        }
        // header params
        if ($session_id !== null) {
            $headerParams['sessionId'] = ObjectSerializer::toHeaderValue($session_id);
        }
        // header params
        if ($session_token !== null) {
            $headerParams['sessionToken'] = ObjectSerializer::toHeaderValue($session_token);
        }
        // header params
        if ($user_id !== null) {
            $headerParams['userId'] = ObjectSerializer::toHeaderValue($user_id);
        }
        // header params
        if ($token !== null) {
            $headerParams['token'] = ObjectSerializer::toHeaderValue($token);
        }
        // header params
        if ($station !== null) {
            $headerParams['station'] = ObjectSerializer::toHeaderValue($station);
        }

        // path params
        if ($document_number !== null) {
            $resourcePath = str_replace(
                '{' . 'documentNumber' . '}',
                ObjectSerializer::toPathValue($document_number),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/pdf']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/pdf'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation salesTransportorderMinutePost
     *
     * Create a freight book based on parameters.
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\Minute $minute minute (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\MinuteResponse
     */
    public function salesTransportorderMinutePost($company_key, $minute, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        list($response) = $this->salesTransportorderMinutePostWithHttpInfo($company_key, $minute, $session_id, $session_token, $user_id, $token, $station);
        return $response;
    }

    /**
     * Operation salesTransportorderMinutePostWithHttpInfo
     *
     * Create a freight book based on parameters.
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\Minute $minute (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\MinuteResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function salesTransportorderMinutePostWithHttpInfo($company_key, $minute, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        $returnType = '\Swagger\Client\Model\MinuteResponse';
        $request = $this->salesTransportorderMinutePostRequest($company_key, $minute, $session_id, $session_token, $user_id, $token, $station);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\MinuteResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation salesTransportorderMinutePostAsync
     *
     * Create a freight book based on parameters.
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\Minute $minute (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function salesTransportorderMinutePostAsync($company_key, $minute, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        return $this->salesTransportorderMinutePostAsyncWithHttpInfo($company_key, $minute, $session_id, $session_token, $user_id, $token, $station)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation salesTransportorderMinutePostAsyncWithHttpInfo
     *
     * Create a freight book based on parameters.
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\Minute $minute (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function salesTransportorderMinutePostAsyncWithHttpInfo($company_key, $minute, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        $returnType = '\Swagger\Client\Model\MinuteResponse';
        $request = $this->salesTransportorderMinutePostRequest($company_key, $minute, $session_id, $session_token, $user_id, $token, $station);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'salesTransportorderMinutePost'
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\Minute $minute (required)
     * @param  float $session_id Session id example \&quot;50836\&quot; (optional)
     * @param  float $session_token Session token example \&quot;3213SADADSAD3121GASAGASDSADADA\&quot; (optional)
     * @param  float $user_id Example \&quot;50836\&quot; (optional)
     * @param  string $token Example \&quot;ease3dsadas1\&quot; (optional)
     * @param  string $station Example \&quot;GRU\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function salesTransportorderMinutePostRequest($company_key, $minute, $session_id = null, $session_token = null, $user_id = null, $token = null, $station = null)
    {
        // verify the required parameter 'company_key' is set
        if ($company_key === null || (is_array($company_key) && count($company_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_key when calling salesTransportorderMinutePost'
            );
        }
        // verify the required parameter 'minute' is set
        if ($minute === null || (is_array($minute) && count($minute) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $minute when calling salesTransportorderMinutePost'
            );
        }

        $resourcePath = '/sales/transportorder/minute';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($company_key !== null) {
            $headerParams['companyKey'] = ObjectSerializer::toHeaderValue($company_key);
        }
        // header params
        if ($session_id !== null) {
            $headerParams['sessionId'] = ObjectSerializer::toHeaderValue($session_id);
        }
        // header params
        if ($session_token !== null) {
            $headerParams['sessionToken'] = ObjectSerializer::toHeaderValue($session_token);
        }
        // header params
        if ($user_id !== null) {
            $headerParams['userId'] = ObjectSerializer::toHeaderValue($user_id);
        }
        // header params
        if ($token !== null) {
            $headerParams['token'] = ObjectSerializer::toHeaderValue($token);
        }
        // header params
        if ($station !== null) {
            $headerParams['station'] = ObjectSerializer::toHeaderValue($station);
        }


        // body params
        $_tempBody = null;
        if (isset($minute)) {
            $_tempBody = $minute;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation salesTransportorderTrackingCustomerdocumentPost
     *
     * Return last action from  transport orders what had status change in the last 3 days by customer document number
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\TrackingByCustomerDocument $model model (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\TrackTransportOrderCustomrDocumentResponse
     */
    public function salesTransportorderTrackingCustomerdocumentPost($company_key, $model = null)
    {
        list($response) = $this->salesTransportorderTrackingCustomerdocumentPostWithHttpInfo($company_key, $model);
        return $response;
    }

    /**
     * Operation salesTransportorderTrackingCustomerdocumentPostWithHttpInfo
     *
     * Return last action from  transport orders what had status change in the last 3 days by customer document number
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\TrackingByCustomerDocument $model (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\TrackTransportOrderCustomrDocumentResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function salesTransportorderTrackingCustomerdocumentPostWithHttpInfo($company_key, $model = null)
    {
        $returnType = '\Swagger\Client\Model\TrackTransportOrderCustomrDocumentResponse';
        $request = $this->salesTransportorderTrackingCustomerdocumentPostRequest($company_key, $model);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\TrackTransportOrderCustomrDocumentResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation salesTransportorderTrackingCustomerdocumentPostAsync
     *
     * Return last action from  transport orders what had status change in the last 3 days by customer document number
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\TrackingByCustomerDocument $model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function salesTransportorderTrackingCustomerdocumentPostAsync($company_key, $model = null)
    {
        return $this->salesTransportorderTrackingCustomerdocumentPostAsyncWithHttpInfo($company_key, $model)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation salesTransportorderTrackingCustomerdocumentPostAsyncWithHttpInfo
     *
     * Return last action from  transport orders what had status change in the last 3 days by customer document number
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\TrackingByCustomerDocument $model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function salesTransportorderTrackingCustomerdocumentPostAsyncWithHttpInfo($company_key, $model = null)
    {
        $returnType = '\Swagger\Client\Model\TrackTransportOrderCustomrDocumentResponse';
        $request = $this->salesTransportorderTrackingCustomerdocumentPostRequest($company_key, $model);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'salesTransportorderTrackingCustomerdocumentPost'
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\TrackingByCustomerDocument $model (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function salesTransportorderTrackingCustomerdocumentPostRequest($company_key, $model = null)
    {
        // verify the required parameter 'company_key' is set
        if ($company_key === null || (is_array($company_key) && count($company_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_key when calling salesTransportorderTrackingCustomerdocumentPost'
            );
        }

        $resourcePath = '/sales/transportorder/tracking/customerdocument';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($company_key !== null) {
            $headerParams['companyKey'] = ObjectSerializer::toHeaderValue($company_key);
        }


        // body params
        $_tempBody = null;
        if (isset($model)) {
            $_tempBody = $model;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                ['application/json', 'text/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation trackingTrackTransportOrder
     *
     * Return all transport order tracking events
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\TrackTransportOrderRequest $model model (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\TrackTransportOrderResponse
     */
    public function trackingTrackTransportOrder($company_key, $model)
    {
        list($response) = $this->trackingTrackTransportOrderWithHttpInfo($company_key, $model);
        return $response;
    }

    /**
     * Operation trackingTrackTransportOrderWithHttpInfo
     *
     * Return all transport order tracking events
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\TrackTransportOrderRequest $model (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\TrackTransportOrderResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function trackingTrackTransportOrderWithHttpInfo($company_key, $model)
    {
        $returnType = '\Swagger\Client\Model\TrackTransportOrderResponse';
        $request = $this->trackingTrackTransportOrderRequest($company_key, $model);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\TrackTransportOrderResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation trackingTrackTransportOrderAsync
     *
     * Return all transport order tracking events
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\TrackTransportOrderRequest $model (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function trackingTrackTransportOrderAsync($company_key, $model)
    {
        return $this->trackingTrackTransportOrderAsyncWithHttpInfo($company_key, $model)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation trackingTrackTransportOrderAsyncWithHttpInfo
     *
     * Return all transport order tracking events
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\TrackTransportOrderRequest $model (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function trackingTrackTransportOrderAsyncWithHttpInfo($company_key, $model)
    {
        $returnType = '\Swagger\Client\Model\TrackTransportOrderResponse';
        $request = $this->trackingTrackTransportOrderRequest($company_key, $model);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'trackingTrackTransportOrder'
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\TrackTransportOrderRequest $model (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function trackingTrackTransportOrderRequest($company_key, $model)
    {
        // verify the required parameter 'company_key' is set
        if ($company_key === null || (is_array($company_key) && count($company_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_key when calling trackingTrackTransportOrder'
            );
        }
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling trackingTrackTransportOrder'
            );
        }

        $resourcePath = '/sales/transportorder/tracking';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($company_key !== null) {
            $headerParams['companyKey'] = ObjectSerializer::toHeaderValue($company_key);
        }


        // body params
        $_tempBody = null;
        if (isset($model)) {
            $_tempBody = $model;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded', 'text/plain', 'text/html']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation xmlTransportOrder
     *
     * Return a CTe XML string by Document Number and Customer Document
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\XMLRequest $model model (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\XMLResponse
     */
    public function xmlTransportOrder($company_key, $model)
    {
        list($response) = $this->xmlTransportOrderWithHttpInfo($company_key, $model);
        return $response;
    }

    /**
     * Operation xmlTransportOrderWithHttpInfo
     *
     * Return a CTe XML string by Document Number and Customer Document
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\XMLRequest $model (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\XMLResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function xmlTransportOrderWithHttpInfo($company_key, $model)
    {
        $returnType = '\Swagger\Client\Model\XMLResponse';
        $request = $this->xmlTransportOrderRequest($company_key, $model);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\XMLResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation xmlTransportOrderAsync
     *
     * Return a CTe XML string by Document Number and Customer Document
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\XMLRequest $model (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function xmlTransportOrderAsync($company_key, $model)
    {
        return $this->xmlTransportOrderAsyncWithHttpInfo($company_key, $model)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation xmlTransportOrderAsyncWithHttpInfo
     *
     * Return a CTe XML string by Document Number and Customer Document
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\XMLRequest $model (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function xmlTransportOrderAsyncWithHttpInfo($company_key, $model)
    {
        $returnType = '\Swagger\Client\Model\XMLResponse';
        $request = $this->xmlTransportOrderRequest($company_key, $model);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'xmlTransportOrder'
     *
     * @param  string $company_key IATA company code example \&quot;G1\&quot; (required)
     * @param  \Swagger\Client\Model\XMLRequest $model (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function xmlTransportOrderRequest($company_key, $model)
    {
        // verify the required parameter 'company_key' is set
        if ($company_key === null || (is_array($company_key) && count($company_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_key when calling xmlTransportOrder'
            );
        }
        // verify the required parameter 'model' is set
        if ($model === null || (is_array($model) && count($model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $model when calling xmlTransportOrder'
            );
        }

        $resourcePath = '/sales/transportorder/xml';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($company_key !== null) {
            $headerParams['companyKey'] = ObjectSerializer::toHeaderValue($company_key);
        }


        // body params
        $_tempBody = null;
        if (isset($model)) {
            $_tempBody = $model;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                ['application/json', 'text/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
