<?php
/**
 * QuotationRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Central do desenvolvedor - Nexlog API
 *
 * De maneira pratica e rápida, entenda como conectar e consumir todas as informações necessárias para seu negócio. </br> <h2> Ambientes</h2> Os ambientes do gateway de integração são divididos atualmente em 2 ambientes:<br> &ensp;&ensp;&ensp;&ensp;&ensp;<b>QA</b>:&ensp;ambiente utilizado para desenvolvimento de novas integrações e testes com os clientes e parceiros.<br>&ensp;&ensp;&ensp;<b>Prod</b>:&ensp;ambiente de produção com todas os serviços expostos com certificação de qualidade. </br> <h2>Informações Adicionais</h2>                 A central do desenvolvedor conta com uma completa documentação referente a todos os APIs expostos, com exemplos de request/response, modelo e possibilidade de realizar testes direto no barramento. </br></br> Atualmente nossa central está separada com 2 dominios de integração:</br>&ensp;&ensp;&ensp; <b>- Account</b> <br> &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Serviços para autenticação quando necessário.</br>&ensp;&ensp;&ensp; <b>- Sales</b> <br> &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Disponibilização de serviços para utilização de rastreio, cotações, minutas e documentos autorizados.<br>&ensp;&ensp;&ensp; <b>- Operations</b> <br> &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Disponibilização de consulta de bases operacionais.<br>(*)Dependendo do endpoint utilizado, algumas informações são obrigatórias, como identificador da aplicação/cliente e token.<br><br> Dúvidas sobre como utilizar, entre em contato br-operations@ttinteractive.com
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * QuotationRequest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuotationRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'QuotationRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'customer_token' => 'string',
        'customer_document' => 'string',
        'origin_point_code' => 'string',
        'origin_postal_code' => 'string',
        'destination_point_code' => 'string',
        'destination_postal_code' => 'string',
        'to_collect' => 'bool',
        'to_delivery' => 'bool',
        'declared_value' => 'int',
        'insurance_type' => 'int',
        'volumes' => '\Swagger\Client\Model\QuotationVolume[]',
        'products' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'customer_token' => null,
        'customer_document' => null,
        'origin_point_code' => null,
        'origin_postal_code' => null,
        'destination_point_code' => null,
        'destination_postal_code' => null,
        'to_collect' => null,
        'to_delivery' => null,
        'declared_value' => 'decimal',
        'insurance_type' => 'int16',
        'volumes' => null,
        'products' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'customer_token' => 'customerToken',
        'customer_document' => 'customerDocument',
        'origin_point_code' => 'originPointCode',
        'origin_postal_code' => 'originPostalCode',
        'destination_point_code' => 'destinationPointCode',
        'destination_postal_code' => 'destinationPostalCode',
        'to_collect' => 'toCollect',
        'to_delivery' => 'toDelivery',
        'declared_value' => 'declaredValue',
        'insurance_type' => 'insuranceType',
        'volumes' => 'volumes',
        'products' => 'products'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'customer_token' => 'setCustomerToken',
        'customer_document' => 'setCustomerDocument',
        'origin_point_code' => 'setOriginPointCode',
        'origin_postal_code' => 'setOriginPostalCode',
        'destination_point_code' => 'setDestinationPointCode',
        'destination_postal_code' => 'setDestinationPostalCode',
        'to_collect' => 'setToCollect',
        'to_delivery' => 'setToDelivery',
        'declared_value' => 'setDeclaredValue',
        'insurance_type' => 'setInsuranceType',
        'volumes' => 'setVolumes',
        'products' => 'setProducts'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'customer_token' => 'getCustomerToken',
        'customer_document' => 'getCustomerDocument',
        'origin_point_code' => 'getOriginPointCode',
        'origin_postal_code' => 'getOriginPostalCode',
        'destination_point_code' => 'getDestinationPointCode',
        'destination_postal_code' => 'getDestinationPostalCode',
        'to_collect' => 'getToCollect',
        'to_delivery' => 'getToDelivery',
        'declared_value' => 'getDeclaredValue',
        'insurance_type' => 'getInsuranceType',
        'volumes' => 'getVolumes',
        'products' => 'getProducts'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['customer_token'] = isset($data['customer_token']) ? $data['customer_token'] : null;
        $this->container['customer_document'] = isset($data['customer_document']) ? $data['customer_document'] : null;
        $this->container['origin_point_code'] = isset($data['origin_point_code']) ? $data['origin_point_code'] : null;
        $this->container['origin_postal_code'] = isset($data['origin_postal_code']) ? $data['origin_postal_code'] : null;
        $this->container['destination_point_code'] = isset($data['destination_point_code']) ? $data['destination_point_code'] : null;
        $this->container['destination_postal_code'] = isset($data['destination_postal_code']) ? $data['destination_postal_code'] : null;
        $this->container['to_collect'] = isset($data['to_collect']) ? $data['to_collect'] : null;
        $this->container['to_delivery'] = isset($data['to_delivery']) ? $data['to_delivery'] : null;
        $this->container['declared_value'] = isset($data['declared_value']) ? $data['declared_value'] : null;
        $this->container['insurance_type'] = isset($data['insurance_type']) ? $data['insurance_type'] : null;
        $this->container['volumes'] = isset($data['volumes']) ? $data['volumes'] : null;
        $this->container['products'] = isset($data['products']) ? $data['products'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets customer_token
     *
     * @return string
     */
    public function getCustomerToken()
    {
        return $this->container['customer_token'];
    }

    /**
     * Sets customer_token
     *
     * @param string $customer_token To indentify de customer, should use customerToken and customerDocument.
     *
     * @return $this
     */
    public function setCustomerToken($customer_token)
    {
        $this->container['customer_token'] = $customer_token;

        return $this;
    }

    /**
     * Gets customer_document
     *
     * @return string
     */
    public function getCustomerDocument()
    {
        return $this->container['customer_document'];
    }

    /**
     * Sets customer_document
     *
     * @param string $customer_document To indentify de customer, should use customerToken and customerDocument.
     *
     * @return $this
     */
    public function setCustomerDocument($customer_document)
    {
        $this->container['customer_document'] = $customer_document;

        return $this;
    }

    /**
     * Gets origin_point_code
     *
     * @return string
     */
    public function getOriginPointCode()
    {
        return $this->container['origin_point_code'];
    }

    /**
     * Sets origin_point_code
     *
     * @param string $origin_point_code Origin point(airport or office) code example \"GRU\".
     *
     * @return $this
     */
    public function setOriginPointCode($origin_point_code)
    {
        $this->container['origin_point_code'] = $origin_point_code;

        return $this;
    }

    /**
     * Gets origin_postal_code
     *
     * @return string
     */
    public function getOriginPostalCode()
    {
        return $this->container['origin_postal_code'];
    }

    /**
     * Sets origin_postal_code
     *
     * @param string $origin_postal_code Origin postal code example \"14000555\".
     *
     * @return $this
     */
    public function setOriginPostalCode($origin_postal_code)
    {
        $this->container['origin_postal_code'] = $origin_postal_code;

        return $this;
    }

    /**
     * Gets destination_point_code
     *
     * @return string
     */
    public function getDestinationPointCode()
    {
        return $this->container['destination_point_code'];
    }

    /**
     * Sets destination_point_code
     *
     * @param string $destination_point_code Destination point(airport or office) code example \"REC\".
     *
     * @return $this
     */
    public function setDestinationPointCode($destination_point_code)
    {
        $this->container['destination_point_code'] = $destination_point_code;

        return $this;
    }

    /**
     * Gets destination_postal_code
     *
     * @return string
     */
    public function getDestinationPostalCode()
    {
        return $this->container['destination_postal_code'];
    }

    /**
     * Sets destination_postal_code
     *
     * @param string $destination_postal_code Destination postal code example \"15000555\".
     *
     * @return $this
     */
    public function setDestinationPostalCode($destination_postal_code)
    {
        $this->container['destination_postal_code'] = $destination_postal_code;

        return $this;
    }

    /**
     * Gets to_collect
     *
     * @return bool
     */
    public function getToCollect()
    {
        return $this->container['to_collect'];
    }

    /**
     * Sets to_collect
     *
     * @param bool $to_collect Set true if is to collect false if not.
     *
     * @return $this
     */
    public function setToCollect($to_collect)
    {
        $this->container['to_collect'] = $to_collect;

        return $this;
    }

    /**
     * Gets to_delivery
     *
     * @return bool
     */
    public function getToDelivery()
    {
        return $this->container['to_delivery'];
    }

    /**
     * Sets to_delivery
     *
     * @param bool $to_delivery Set true if is to delivery false if not.
     *
     * @return $this
     */
    public function setToDelivery($to_delivery)
    {
        $this->container['to_delivery'] = $to_delivery;

        return $this;
    }

    /**
     * Gets declared_value
     *
     * @return int
     */
    public function getDeclaredValue()
    {
        return $this->container['declared_value'];
    }

    /**
     * Sets declared_value
     *
     * @param int $declared_value Goods total value for insurance purpose.
     *
     * @return $this
     */
    public function setDeclaredValue($declared_value)
    {
        $this->container['declared_value'] = $declared_value;

        return $this;
    }

    /**
     * Gets insurance_type
     *
     * @return int
     */
    public function getInsuranceType()
    {
        return $this->container['insurance_type'];
    }

    /**
     * Sets insurance_type
     *
     * @param int $insurance_type Insurance Type:  * 0 - Customer  * 1 - Company  * 2 - Uninsured
     *
     * @return $this
     */
    public function setInsuranceType($insurance_type)
    {
        $this->container['insurance_type'] = $insurance_type;

        return $this;
    }

    /**
     * Gets volumes
     *
     * @return \Swagger\Client\Model\QuotationVolume[]
     */
    public function getVolumes()
    {
        return $this->container['volumes'];
    }

    /**
     * Sets volumes
     *
     * @param \Swagger\Client\Model\QuotationVolume[] $volumes volumes
     *
     * @return $this
     */
    public function setVolumes($volumes)
    {
        $this->container['volumes'] = $volumes;

        return $this;
    }

    /**
     * Gets products
     *
     * @return string[]
     */
    public function getProducts()
    {
        return $this->container['products'];
    }

    /**
     * Sets products
     *
     * @param string[] $products Array of services code to quote example \"NOR, DGS\"
     *
     * @return $this
     */
    public function setProducts($products)
    {
        $this->container['products'] = $products;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


