<?php
/**
 * QuotationResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Central do desenvolvedor - Nexlog API
 *
 * De maneira pratica e rápida, entenda como conectar e consumir todas as informações necessárias para seu negócio. </br> <h2> Ambientes</h2> Os ambientes do gateway de integração são divididos atualmente em 2 ambientes:<br> &ensp;&ensp;&ensp;&ensp;&ensp;<b>QA</b>:&ensp;ambiente utilizado para desenvolvimento de novas integrações e testes com os clientes e parceiros.<br>&ensp;&ensp;&ensp;<b>Prod</b>:&ensp;ambiente de produção com todas os serviços expostos com certificação de qualidade. </br> <h2>Informações Adicionais</h2>                 A central do desenvolvedor conta com uma completa documentação referente a todos os APIs expostos, com exemplos de request/response, modelo e possibilidade de realizar testes direto no barramento. </br></br> Atualmente nossa central está separada com 2 dominios de integração:</br>&ensp;&ensp;&ensp; <b>- Account</b> <br> &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Serviços para autenticação quando necessário.</br>&ensp;&ensp;&ensp; <b>- Sales</b> <br> &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Disponibilização de serviços para utilização de rastreio, cotações, minutas e documentos autorizados.<br>&ensp;&ensp;&ensp; <b>- Operations</b> <br> &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Disponibilização de consulta de bases operacionais.<br>(*)Dependendo do endpoint utilizado, algumas informações são obrigatórias, como identificador da aplicação/cliente e token.<br><br> Dúvidas sobre como utilizar, entre em contato br-operations@ttinteractive.com
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * QuotationResponse Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuotationResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'QuotationResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id_quotation' => 'string',
        'origin_point_code' => 'string',
        'origin_postal_code' => 'string',
        'origin_point_description' => 'string',
        'destination_point_code' => 'string',
        'destination_postal_code' => 'string',
        'destination_point_description' => 'string',
        'service_code' => 'string',
        'service_description' => 'string',
        'declared_value' => 'float',
        'payment_method_description' => 'string',
        'agreement_info' => 'string',
        'volumes' => '\Swagger\Client\Model\Volume[]',
        'total_chargeable_weight' => 'float',
        'freight_value' => 'float',
        'charges_value' => 'float',
        'total_value' => 'float',
        'infos' => '\Swagger\Client\Model\Info'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id_quotation' => null,
        'origin_point_code' => null,
        'origin_postal_code' => null,
        'origin_point_description' => null,
        'destination_point_code' => null,
        'destination_postal_code' => null,
        'destination_point_description' => null,
        'service_code' => null,
        'service_description' => null,
        'declared_value' => 'decimal',
        'payment_method_description' => null,
        'agreement_info' => null,
        'volumes' => null,
        'total_chargeable_weight' => 'decimal',
        'freight_value' => 'decimal',
        'charges_value' => 'decimal',
        'total_value' => 'decimal',
        'infos' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_quotation' => 'idQuotation',
        'origin_point_code' => 'originPointCode',
        'origin_postal_code' => 'originPostalCode',
        'origin_point_description' => 'originPointDescription',
        'destination_point_code' => 'destinationPointCode',
        'destination_postal_code' => 'destinationPostalCode',
        'destination_point_description' => 'destinationPointDescription',
        'service_code' => 'serviceCode',
        'service_description' => 'serviceDescription',
        'declared_value' => 'declaredValue',
        'payment_method_description' => 'paymentMethodDescription',
        'agreement_info' => 'agreementInfo',
        'volumes' => 'volumes',
        'total_chargeable_weight' => 'totalChargeableWeight',
        'freight_value' => 'freightValue',
        'charges_value' => 'chargesValue',
        'total_value' => 'totalValue',
        'infos' => 'infos'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_quotation' => 'setIdQuotation',
        'origin_point_code' => 'setOriginPointCode',
        'origin_postal_code' => 'setOriginPostalCode',
        'origin_point_description' => 'setOriginPointDescription',
        'destination_point_code' => 'setDestinationPointCode',
        'destination_postal_code' => 'setDestinationPostalCode',
        'destination_point_description' => 'setDestinationPointDescription',
        'service_code' => 'setServiceCode',
        'service_description' => 'setServiceDescription',
        'declared_value' => 'setDeclaredValue',
        'payment_method_description' => 'setPaymentMethodDescription',
        'agreement_info' => 'setAgreementInfo',
        'volumes' => 'setVolumes',
        'total_chargeable_weight' => 'setTotalChargeableWeight',
        'freight_value' => 'setFreightValue',
        'charges_value' => 'setChargesValue',
        'total_value' => 'setTotalValue',
        'infos' => 'setInfos'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_quotation' => 'getIdQuotation',
        'origin_point_code' => 'getOriginPointCode',
        'origin_postal_code' => 'getOriginPostalCode',
        'origin_point_description' => 'getOriginPointDescription',
        'destination_point_code' => 'getDestinationPointCode',
        'destination_postal_code' => 'getDestinationPostalCode',
        'destination_point_description' => 'getDestinationPointDescription',
        'service_code' => 'getServiceCode',
        'service_description' => 'getServiceDescription',
        'declared_value' => 'getDeclaredValue',
        'payment_method_description' => 'getPaymentMethodDescription',
        'agreement_info' => 'getAgreementInfo',
        'volumes' => 'getVolumes',
        'total_chargeable_weight' => 'getTotalChargeableWeight',
        'freight_value' => 'getFreightValue',
        'charges_value' => 'getChargesValue',
        'total_value' => 'getTotalValue',
        'infos' => 'getInfos'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id_quotation'] = isset($data['id_quotation']) ? $data['id_quotation'] : null;
        $this->container['origin_point_code'] = isset($data['origin_point_code']) ? $data['origin_point_code'] : null;
        $this->container['origin_postal_code'] = isset($data['origin_postal_code']) ? $data['origin_postal_code'] : null;
        $this->container['origin_point_description'] = isset($data['origin_point_description']) ? $data['origin_point_description'] : null;
        $this->container['destination_point_code'] = isset($data['destination_point_code']) ? $data['destination_point_code'] : null;
        $this->container['destination_postal_code'] = isset($data['destination_postal_code']) ? $data['destination_postal_code'] : null;
        $this->container['destination_point_description'] = isset($data['destination_point_description']) ? $data['destination_point_description'] : null;
        $this->container['service_code'] = isset($data['service_code']) ? $data['service_code'] : null;
        $this->container['service_description'] = isset($data['service_description']) ? $data['service_description'] : null;
        $this->container['declared_value'] = isset($data['declared_value']) ? $data['declared_value'] : null;
        $this->container['payment_method_description'] = isset($data['payment_method_description']) ? $data['payment_method_description'] : null;
        $this->container['agreement_info'] = isset($data['agreement_info']) ? $data['agreement_info'] : null;
        $this->container['volumes'] = isset($data['volumes']) ? $data['volumes'] : null;
        $this->container['total_chargeable_weight'] = isset($data['total_chargeable_weight']) ? $data['total_chargeable_weight'] : null;
        $this->container['freight_value'] = isset($data['freight_value']) ? $data['freight_value'] : null;
        $this->container['charges_value'] = isset($data['charges_value']) ? $data['charges_value'] : null;
        $this->container['total_value'] = isset($data['total_value']) ? $data['total_value'] : null;
        $this->container['infos'] = isset($data['infos']) ? $data['infos'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_quotation
     *
     * @return string
     */
    public function getIdQuotation()
    {
        return $this->container['id_quotation'];
    }

    /**
     * Sets id_quotation
     *
     * @param string $id_quotation id_quotation
     *
     * @return $this
     */
    public function setIdQuotation($id_quotation)
    {
        $this->container['id_quotation'] = $id_quotation;

        return $this;
    }

    /**
     * Gets origin_point_code
     *
     * @return string
     */
    public function getOriginPointCode()
    {
        return $this->container['origin_point_code'];
    }

    /**
     * Sets origin_point_code
     *
     * @param string $origin_point_code Origin point(airport or office) code example \"GRU\".
     *
     * @return $this
     */
    public function setOriginPointCode($origin_point_code)
    {
        $this->container['origin_point_code'] = $origin_point_code;

        return $this;
    }

    /**
     * Gets origin_postal_code
     *
     * @return string
     */
    public function getOriginPostalCode()
    {
        return $this->container['origin_postal_code'];
    }

    /**
     * Sets origin_postal_code
     *
     * @param string $origin_postal_code Origin postal code example \"14000555\".
     *
     * @return $this
     */
    public function setOriginPostalCode($origin_postal_code)
    {
        $this->container['origin_postal_code'] = $origin_postal_code;

        return $this;
    }

    /**
     * Gets origin_point_description
     *
     * @return string
     */
    public function getOriginPointDescription()
    {
        return $this->container['origin_point_description'];
    }

    /**
     * Sets origin_point_description
     *
     * @param string $origin_point_description Origin point name example \"GRU - CARGAS S/A\",
     *
     * @return $this
     */
    public function setOriginPointDescription($origin_point_description)
    {
        $this->container['origin_point_description'] = $origin_point_description;

        return $this;
    }

    /**
     * Gets destination_point_code
     *
     * @return string
     */
    public function getDestinationPointCode()
    {
        return $this->container['destination_point_code'];
    }

    /**
     * Sets destination_point_code
     *
     * @param string $destination_point_code Destination point(airport or office) code example \"REC\".
     *
     * @return $this
     */
    public function setDestinationPointCode($destination_point_code)
    {
        $this->container['destination_point_code'] = $destination_point_code;

        return $this;
    }

    /**
     * Gets destination_postal_code
     *
     * @return string
     */
    public function getDestinationPostalCode()
    {
        return $this->container['destination_postal_code'];
    }

    /**
     * Sets destination_postal_code
     *
     * @param string $destination_postal_code Destination postal code example \"15000555\".
     *
     * @return $this
     */
    public function setDestinationPostalCode($destination_postal_code)
    {
        $this->container['destination_postal_code'] = $destination_postal_code;

        return $this;
    }

    /**
     * Gets destination_point_description
     *
     * @return string
     */
    public function getDestinationPointDescription()
    {
        return $this->container['destination_point_description'];
    }

    /**
     * Sets destination_point_description
     *
     * @param string $destination_point_description Destination point name example \"REC - CARGAS S/A\".
     *
     * @return $this
     */
    public function setDestinationPointDescription($destination_point_description)
    {
        $this->container['destination_point_description'] = $destination_point_description;

        return $this;
    }

    /**
     * Gets service_code
     *
     * @return string
     */
    public function getServiceCode()
    {
        return $this->container['service_code'];
    }

    /**
     * Sets service_code
     *
     * @param string $service_code Service code example \"NOR\".
     *
     * @return $this
     */
    public function setServiceCode($service_code)
    {
        $this->container['service_code'] = $service_code;

        return $this;
    }

    /**
     * Gets service_description
     *
     * @return string
     */
    public function getServiceDescription()
    {
        return $this->container['service_description'];
    }

    /**
     * Sets service_description
     *
     * @param string $service_description Service name example \"NORMAL FREIGHT\".
     *
     * @return $this
     */
    public function setServiceDescription($service_description)
    {
        $this->container['service_description'] = $service_description;

        return $this;
    }

    /**
     * Gets declared_value
     *
     * @return float
     */
    public function getDeclaredValue()
    {
        return $this->container['declared_value'];
    }

    /**
     * Sets declared_value
     *
     * @param float $declared_value Declared value example \"\".
     *
     * @return $this
     */
    public function setDeclaredValue($declared_value)
    {
        $this->container['declared_value'] = $declared_value;

        return $this;
    }

    /**
     * Gets payment_method_description
     *
     * @return string
     */
    public function getPaymentMethodDescription()
    {
        return $this->container['payment_method_description'];
    }

    /**
     * Sets payment_method_description
     *
     * @param string $payment_method_description Payment method name example \"Pre Paid\"
     *
     * @return $this
     */
    public function setPaymentMethodDescription($payment_method_description)
    {
        $this->container['payment_method_description'] = $payment_method_description;

        return $this;
    }

    /**
     * Gets agreement_info
     *
     * @return string
     */
    public function getAgreementInfo()
    {
        return $this->container['agreement_info'];
    }

    /**
     * Sets agreement_info
     *
     * @param string $agreement_info Agreement example \"AGREEMENT XX\"
     *
     * @return $this
     */
    public function setAgreementInfo($agreement_info)
    {
        $this->container['agreement_info'] = $agreement_info;

        return $this;
    }

    /**
     * Gets volumes
     *
     * @return \Swagger\Client\Model\Volume[]
     */
    public function getVolumes()
    {
        return $this->container['volumes'];
    }

    /**
     * Sets volumes
     *
     * @param \Swagger\Client\Model\Volume[] $volumes volumes
     *
     * @return $this
     */
    public function setVolumes($volumes)
    {
        $this->container['volumes'] = $volumes;

        return $this;
    }

    /**
     * Gets total_chargeable_weight
     *
     * @return float
     */
    public function getTotalChargeableWeight()
    {
        return $this->container['total_chargeable_weight'];
    }

    /**
     * Sets total_chargeable_weight
     *
     * @param float $total_chargeable_weight Total chargeable weight example 3.000
     *
     * @return $this
     */
    public function setTotalChargeableWeight($total_chargeable_weight)
    {
        $this->container['total_chargeable_weight'] = $total_chargeable_weight;

        return $this;
    }

    /**
     * Gets freight_value
     *
     * @return float
     */
    public function getFreightValue()
    {
        return $this->container['freight_value'];
    }

    /**
     * Sets freight_value
     *
     * @param float $freight_value Freight value without tax and charges.
     *
     * @return $this
     */
    public function setFreightValue($freight_value)
    {
        $this->container['freight_value'] = $freight_value;

        return $this;
    }

    /**
     * Gets charges_value
     *
     * @return float
     */
    public function getChargesValue()
    {
        return $this->container['charges_value'];
    }

    /**
     * Sets charges_value
     *
     * @param float $charges_value Charges and taxes.
     *
     * @return $this
     */
    public function setChargesValue($charges_value)
    {
        $this->container['charges_value'] = $charges_value;

        return $this;
    }

    /**
     * Gets total_value
     *
     * @return float
     */
    public function getTotalValue()
    {
        return $this->container['total_value'];
    }

    /**
     * Sets total_value
     *
     * @param float $total_value Total value is a sum of freight value and charges
     *
     * @return $this
     */
    public function setTotalValue($total_value)
    {
        $this->container['total_value'] = $total_value;

        return $this;
    }

    /**
     * Gets infos
     *
     * @return \Swagger\Client\Model\Info
     */
    public function getInfos()
    {
        return $this->container['infos'];
    }

    /**
     * Sets infos
     *
     * @param \Swagger\Client\Model\Info $infos infos
     *
     * @return $this
     */
    public function setInfos($infos)
    {
        $this->container['infos'] = $infos;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


