<?php
/**
 * QuotationResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Central do desenvolvedor - Nexlog API
 *
 * De maneira pratica e rápida, entenda como conectar e consumir todas as informações necessárias para seu negócio. </br> <h2> Ambientes</h2> Os ambientes do gateway de integração são divididos atualmente em 2 ambientes:<br> &ensp;&ensp;&ensp;&ensp;&ensp;<b>QA</b>:&ensp;ambiente utilizado para desenvolvimento de novas integrações e testes com os clientes e parceiros.<br>&ensp;&ensp;&ensp;<b>Prod</b>:&ensp;ambiente de produção com todas os serviços expostos com certificação de qualidade. </br> <h2>Informações Adicionais</h2>                 A central do desenvolvedor conta com uma completa documentação referente a todos os APIs expostos, com exemplos de request/response, modelo e possibilidade de realizar testes direto no barramento. </br></br> Atualmente nossa central está separada com 2 dominios de integração:</br>&ensp;&ensp;&ensp; <b>- Account</b> <br> &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Serviços para autenticação quando necessário.</br>&ensp;&ensp;&ensp; <b>- Sales</b> <br> &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Disponibilização de serviços para utilização de rastreio, cotações, minutas e documentos autorizados.<br>&ensp;&ensp;&ensp; <b>- Operations</b> <br> &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;Disponibilização de consulta de bases operacionais.<br>(*)Dependendo do endpoint utilizado, algumas informações são obrigatórias, como identificador da aplicação/cliente e token.<br><br> Dúvidas sobre como utilizar, entre em contato br-operations@ttinteractive.com
 *
 * OpenAPI spec version: V1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QuotationResponseTest Class Doc Comment
 *
 * @category    Class
 * @description QuotationResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuotationResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QuotationResponse"
     */
    public function testQuotationResponse()
    {
    }

    /**
     * Test attribute "id_quotation"
     */
    public function testPropertyIdQuotation()
    {
    }

    /**
     * Test attribute "origin_point_code"
     */
    public function testPropertyOriginPointCode()
    {
    }

    /**
     * Test attribute "origin_postal_code"
     */
    public function testPropertyOriginPostalCode()
    {
    }

    /**
     * Test attribute "origin_point_description"
     */
    public function testPropertyOriginPointDescription()
    {
    }

    /**
     * Test attribute "destination_point_code"
     */
    public function testPropertyDestinationPointCode()
    {
    }

    /**
     * Test attribute "destination_postal_code"
     */
    public function testPropertyDestinationPostalCode()
    {
    }

    /**
     * Test attribute "destination_point_description"
     */
    public function testPropertyDestinationPointDescription()
    {
    }

    /**
     * Test attribute "service_code"
     */
    public function testPropertyServiceCode()
    {
    }

    /**
     * Test attribute "service_description"
     */
    public function testPropertyServiceDescription()
    {
    }

    /**
     * Test attribute "declared_value"
     */
    public function testPropertyDeclaredValue()
    {
    }

    /**
     * Test attribute "payment_method_description"
     */
    public function testPropertyPaymentMethodDescription()
    {
    }

    /**
     * Test attribute "agreement_info"
     */
    public function testPropertyAgreementInfo()
    {
    }

    /**
     * Test attribute "volumes"
     */
    public function testPropertyVolumes()
    {
    }

    /**
     * Test attribute "total_chargeable_weight"
     */
    public function testPropertyTotalChargeableWeight()
    {
    }

    /**
     * Test attribute "freight_value"
     */
    public function testPropertyFreightValue()
    {
    }

    /**
     * Test attribute "charges_value"
     */
    public function testPropertyChargesValue()
    {
    }

    /**
     * Test attribute "total_value"
     */
    public function testPropertyTotalValue()
    {
    }

    /**
     * Test attribute "infos"
     */
    public function testPropertyInfos()
    {
    }
}
